/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddArea: typeof import('./src/components/dialogs/AddArea.vue')['default']
    AddCity: typeof import('./src/components/dialogs/AddCity.vue')['default']
    AddCountry: typeof import('./src/components/dialogs/AddCountry.vue')['default']
    AddUser: typeof import('./src/components/dialogs/AddUser.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ConfirmDialog: typeof import('./src/components/dialogs/ConfirmDialog.vue')['default']
    DeleteConfirmationDialog: typeof import('./src/components/DeleteConfirmationDialog.vue')['default']
    EditDialog: typeof import('./src/components/user/EditDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageTitleComponent: typeof import('./src/components/PageTitleComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TravelerLogo: typeof import('./src/components/TravelerLogo.vue')['default']
  }
}
