/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/countries/': RouteRecordInfo<'/countries/', '/countries', Record<never, never>, Record<never, never>>,
    '/countries/[id]/': RouteRecordInfo<'/countries/[id]/', '/countries/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/countries/[id]/[id]': RouteRecordInfo<'/countries/[id]/[id]', '/countries/:id/:id', { id: ParamValue<true>, id: ParamValue<true> }, { id: ParamValue<false>, id: ParamValue<false> }>,
    '/countries/[id]/create': RouteRecordInfo<'/countries/[id]/create', '/countries/:id/create', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/countries/components/CountryFormDialog': RouteRecordInfo<'/countries/components/CountryFormDialog', '/countries/components/CountryFormDialog', Record<never, never>, Record<never, never>>,
    '/countries/components/DeleteConfirmationDialog': RouteRecordInfo<'/countries/components/DeleteConfirmationDialog', '/countries/components/DeleteConfirmationDialog', Record<never, never>, Record<never, never>>,
    '/countries/create': RouteRecordInfo<'/countries/create', '/countries/create', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/components/ConfirmationDialog': RouteRecordInfo<'/users/components/ConfirmationDialog', '/users/components/ConfirmationDialog', Record<never, never>, Record<never, never>>,
    '/users/create': RouteRecordInfo<'/users/create', '/users/create', Record<never, never>, Record<never, never>>,
    '/users/usersDetails': RouteRecordInfo<'/users/usersDetails', '/users/usersDetails', Record<never, never>, Record<never, never>>,
  }
}
